[[mgr.prepend_keymap]]
on = "<Tab>"
run = "cd --interactive"
desc = "Jump interactivly"

[[mgr.prepend_keymap]]
on = "s"
run = "plugin fzf"
desc = "fzf"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin zoxide"
desc = "zoxide"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Documents/"
desc = "Cd to Documents"

[[mgr.prepend_keymap]]
on   = [ "g", "C" ]
run  = "cd ~/Documents/Code/"
desc = "Cd to Code"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Documents/Studium/Semester_4/"
desc = "Cd to Studium"

[[mgr.prepend_keymap]]
on   = [ "g", "S" ]
run  = "cd ~/Documents/Screenshots/"
desc = "Cd to Screenshots"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd ~/.Trash/"
desc = "Cd to Trash"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Library/Mobile\\ Documents/com~apple~CloudDocs/Work/"
desc = "Cd to Work"

[[mgr.prepend_keymap]]
on = "ø"
run = 'shell --block -- vi +"nnoremap q :conf q<CR> | nnoremap f /| set ignorecase | set number | set relativenumber | set clipboard=unnamed | set runtimepath+=~/.config/vim | syntax on | colorscheme GruberDarker" -i NONE "$0"'

[[mgr.prepend_keymap]]
on = "√"
run = 'shell --block -- vd "$0"'
