return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "vim",
      "java",
      "javadoc",
      "go",
      "gomod",
      "vimdoc",
      "typst",
      "markdown",
      "markdown_inline",
      "latex",
      "bibtex",
      "yaml",
      "xml",
      "typescript",
      "dot",
      "toml",
      "tmux",
      "swift",
      "sql",
      "rust",
      "regex",
      "r",
      "python",
      "php",
      "json",
      "html",
      "css",
      "scala",
      "bash",
      "c",
      "fish",
      "make",
    },
    highlight = {
      enable = true,
    },
  },
}
