theme = "gruber-darker"

[editor]
line-number = "relative"
mouse = false
scrolloff = 7
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
 
